// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8TVT7JZD2aMnDIC0ldpFYepwBSsFRyOA',
    appId: '1:721927092605:web:0a1e8344e968a4a2acf414',
    messagingSenderId: '721927092605',
    projectId: 'bank-app-424c8',
    authDomain: 'bank-app-424c8.firebaseapp.com',
    databaseURL: 'https://bank-app-424c8-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-424c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwGWiA0yUEJhO-CtLU3LwyP6ta1hnamQk',
    appId: '1:721927092605:android:f3372d431c336c6facf414',
    messagingSenderId: '721927092605',
    projectId: 'bank-app-424c8',
    databaseURL: 'https://bank-app-424c8-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-424c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_Bv4FIXEWZabpERoOm5SGXIh8x9f12E',
    appId: '1:721927092605:ios:fc868011fc449c5eacf414',
    messagingSenderId: '721927092605',
    projectId: 'bank-app-424c8',
    databaseURL: 'https://bank-app-424c8-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-424c8.firebasestorage.app',
    iosBundleId: 'com.example.bankApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_Bv4FIXEWZabpERoOm5SGXIh8x9f12E',
    appId: '1:721927092605:ios:fc868011fc449c5eacf414',
    messagingSenderId: '721927092605',
    projectId: 'bank-app-424c8',
    databaseURL: 'https://bank-app-424c8-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-424c8.firebasestorage.app',
    iosBundleId: 'com.example.bankApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8TVT7JZD2aMnDIC0ldpFYepwBSsFRyOA',
    appId: '1:721927092605:web:6ab7891ce7147e2aacf414',
    messagingSenderId: '721927092605',
    projectId: 'bank-app-424c8',
    authDomain: 'bank-app-424c8.firebaseapp.com',
    databaseURL: 'https://bank-app-424c8-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-424c8.firebasestorage.app',
  );
}
